local function Blinktop()  -- Program for Blink Tips
    gpio.write(morse_led, gpio.LOW)
    tmr.delay(500000)
    gpio.write(morse_led, gpio.HIGH)
    tmr.delay(500000)
end 

local function UpOneByOne()
    pwm.setduty(r_a, 1000 )
    Blinktop()
    pwm.setduty(r_b, 1000 )
    Blinktop()
    pwm.setduty(y_a, 1000 )
    Blinktop()
    pwm.setduty(y_b, 1000 )
    Blinktop()
    pwm.setduty(g_a, 1000 )
    Blinktop()
    pwm.setduty(g_b, 1000 )
    Blinktop()
end

local function UpOneChip()
    pwm.setduty(r_a, 1000 )
    Blinktop()
    pwm.setduty(y_a, 1000 )
    Blinktop()
    pwm.setduty(g_a, 1000 )
    Blinktop()
    pwm.setduty(r_a, 0 )
    pwm.setduty(y_a, 0 )
    pwm.setduty(g_a, 0 )
    Blinktop()
    pwm.setduty(r_b, 1000 )
    Blinktop()
    pwm.setduty(y_b, 1000 )
    Blinktop()
    pwm.setduty(g_b, 1000 )
    Blinktop()
    pwm.setduty(r_b, 0 )
    pwm.setduty(y_b, 0 )
    pwm.setduty(g_b, 0 )
    Blinktop()
end

local function UpOneColor()
    pwm.setduty(r_a, 1000 )
    Blinktop()
    pwm.setduty(r_b, 1000 )
    Blinktop()
    pwm.setduty(r_a, 0 )
    pwm.setduty(r_b, 0 )
    
    pwm.setduty(y_a, 1000 )
    Blinktop()
    pwm.setduty(y_b, 1000 )
    Blinktop()
    pwm.setduty(y_a, 0 )
    pwm.setduty(y_b, 0 )
    
    pwm.setduty(g_a, 1000 )
    Blinktop()
    pwm.setduty(g_b, 1000 )
    Blinktop()
    pwm.setduty(r_a, 0 )
    pwm.setduty(y_a, 0 )
    pwm.setduty(g_a, 0 )
    pwm.setduty(r_b, 0 )
    pwm.setduty(y_b, 0 )
    pwm.setduty(g_b, 0 )
    Blinktop()
end

local function UpBothChip()
    pwm.setduty(r_a, 1000 )
    Blinktop()
    pwm.setduty(y_b, 1000 )
    Blinktop()
    pwm.setduty(g_a, 1000 )
    Blinktop()
    pwm.setduty(r_b, 1000 )
    Blinktop()
    pwm.setduty(y_a, 1000 )
    Blinktop()
    pwm.setduty(g_b, 1000 )
    Blinktop()
    pwm.setduty(r_a, 0 )
    pwm.setduty(y_a, 0 )
    pwm.setduty(g_a, 0 )
    pwm.setduty(r_b, 0 )
    pwm.setduty(y_b, 0 )
    pwm.setduty(g_b, 0 )
    Blinktop()
end


pwm.setduty(r_a, 0 )
pwm.setduty(y_a, 0 )
pwm.setduty(g_a, 0 )
pwm.setduty(r_b, 0 )
pwm.setduty(y_b, 0 )
pwm.setduty(g_b, 0 )
UpOneColor()
UpOneChip()
UpBothChip()
UpOneByOne()